/**
 * @File Name          : MotivoExtension.cls
 * @Description        : 
 * @Author             : ismael.ocana@s4g.es
 * @Group              : 
 * @Last Modified By   : ismael.ocana@s4g.es
 * @Last Modified On   : 17/10/2019 9:23:17
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    17/10/2019   ismael.ocana@s4g.es     Initial Version
**/
public with sharing class MotivoExtension {
    
    public String value {get;set;}

    public MotivoExtension(ApexPages.StandardController controller){

    }
}